### PR TITLE
copy site html from src to dist

### PR DESCRIPTION
**Pull request by gavinpatkinson**
- actually copy html from src to dist

### CODE REVIEW

**Comment by msutherl** [comment]
re: #15 happy to help!

With this branch merged, I'm getting the same errors:

Screenshot 2019-04-09 15 39 38

and the site appears to load, however with horizontal scroll at certain widths i.e. ~2600px, which seems wrong, and broken links. Do you think this is build-related or is that the state of the app currently?

Screenshot 2019-04-09 15 38 22

**Comment by gavinpatkinson** [comment]
Not sure why the 'this' keyword message is appearing, although its not an error. The npm audit thing is safe to ignore for now.

I don't get any horizontal scrolling on my end, are you using chrome?

This is the state of the site, nothing has really been built. I started making it to test the utility classes.

**Comment by msutherl** [comment]
@gavinpatkinson ok, great (sorry, I meant "warnings") – I'll file an issue about the horizontal scroll

**Comment by msutherl** [comment]
https://github.com/urbit/indigo/issues/17

**Pull request merged**
