### PR TITLE
replace broken gulp-better-rollup link in package.json

### PR DESCRIPTION
**Pull request by msutherl**
I'm not sure if this is the right fix, but I had the following error when running `npm install`:

```
Unhandled rejection Error: Command failed: /usr/local/bin/git checkout greenkeeper/rollup-0.67.3
error: pathspec 'greenkeeper/rollup-0.67.3' did not match any file(s) known to git
```

Manually removed and reinstalled `gulp-better-rollup` and `npm install` finished without errors.

### CODE REVIEW

**Comment by msutherl** [comment]
Scratch that, this mucked with peer dependencies. Investigating.

**Comment by jyng** [comment]
@msutherl I also ran into this issue, not sure the best way to solve this

**Comment by msutherl** [comment]
@jyng @gavinpatkinson what node version should I use with this repo? Looks like it was at `10.12.21`?

**Comment by gavinpatkinson** [comment]
i'll take a look

**Comment by jyng** [comment]
I'm using `10.15.3 LTS` which is the latest version i believe. I don't think it's a node issue, my hunch is that its a syntax error in the `gulp-better-rollup` dependency.

**Comment by gavinpatkinson** [comment]
I'm using 10.0.0

**Comment by gavinpatkinson** [comment]
Please try this branch and tell me if it works.

https://github.com/urbit/indigo/tree/rollup-fix

don't forget to rm -rf  your node_modules

**Comment by gavinpatkinson** [comment]
This sort of error happens when a package is added to package.json that isn't reachable by the package manager. In this case, the greenkeeper branch of gulp-better-rollup no longer exists. gulp-better-rollup also requires rollup, as stated in their docs.

**Comment by gavinpatkinson** [comment]
Since it appears to work I have merged my fix branch
https://github.com/urbit/indigo/pull/15

**Pull request closed without merging**
