### PR TITLE
fix rollup

### PR DESCRIPTION
**Pull request by gavinpatkinson**

### CODE REVIEW

**Comment by gavinpatkinson** [comment]
This also fixed travis, so I'm just going to merge it @jyng @msutherl

**Comment by msutherl** [comment]
I ended up making similar changes locally and ended up in the same place I am trying to run `gulp site` with these changes. See log below.

Screenshot 2019-04-09 15 18 17

**Comment by gavinpatkinson** [comment]
try copying the html file from src into dest

**Comment by gavinpatkinson** [comment]
resolved here, will PR in a sec
https://github.com/urbit/indigo/pull/16

**Comment by gavinpatkinson** [comment]
Thanks for working with me on this! Its the first time anyone else has really used this. Happy to hear suggestions on how the readme could be improved too.

**Comment by msutherl** [comment]
> Thanks for working with me on this! Its the first time anyone else has really used this. Happy to hear suggestions on how the readme could be improved too.

Thanks for the quick response! The README was very helpful for what I was trying to do – thanks for laying everything out clearly.

The main upstream question I had while trying to resolve dependency issues was what node version I should be using.

**Pull request merged**
